"""Initial migration

Revision ID: 0215b9f4c937
Revises: 
Create Date: 2021-11-24 15:03:29.879327

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0215b9f4c937'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('films_genres')
    op.drop_table('directors')
    op.drop_table('genres')
    op.drop_table('films')
    op.drop_table('users')
    op.drop_table('films_directors')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('films_directors',
    sa.Column('film_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('director_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['director_id'], ['directors.director_id'], name='films_directors_director_id_fkey', ondelete='SET DEFAULT'),
    sa.ForeignKeyConstraint(['film_id'], ['films.film_id'], name='films_directors_film_id_fkey'),
    sa.PrimaryKeyConstraint('film_id', 'director_id', name='films_directors_pkey')
    )
    op.create_table('users',
    sa.Column('user_id', sa.INTEGER(), server_default=sa.text("nextval('users_user_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=80), autoincrement=False, nullable=False),
    sa.Column('surname', sa.VARCHAR(length=80), autoincrement=False, nullable=False),
    sa.Column('login', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('password', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('is_admin', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('user_id', name='users_pkey'),
    sa.UniqueConstraint('login', name='users_login_key'),
    postgresql_ignore_search_path=False
    )
    op.create_table('films',
    sa.Column('film_id', sa.INTEGER(), server_default=sa.text("nextval('films_film_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('title', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('release_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('rating', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('poster', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], name='films_user_id_fkey'),
    sa.PrimaryKeyConstraint('film_id', name='films_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('genres',
    sa.Column('genre_id', sa.INTEGER(), server_default=sa.text("nextval('genres_genre_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=80), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('genre_id', name='genres_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('directors',
    sa.Column('director_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=80), autoincrement=False, nullable=False),
    sa.Column('surname', sa.VARCHAR(length=80), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('director_id', name='directors_pkey')
    )
    op.create_table('films_genres',
    sa.Column('film_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('genre_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['film_id'], ['films.film_id'], name='films_genres_film_id_fkey'),
    sa.ForeignKeyConstraint(['genre_id'], ['genres.genre_id'], name='films_genres_genre_id_fkey'),
    sa.PrimaryKeyConstraint('film_id', 'genre_id', name='films_genres_pkey')
    )
    # ### end Alembic commands ###
